# fly.toml app configuration file generated for server-blue-dust-1345 on 2025-03-02T11:09:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-blue-dust-1345'
primary_region = 'den'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
